### ISSUE TITLE
Some question about the pre-computed camera coordinate files (/eye/)

### ISSUE THREAD

**Issue by tdd233** [TOPO-EPFL/CrossLoc-Benchmark-Datasets#5]
Hi Qi,
  Sorry to bother you again. I noticed that there are 2 modes to estimate camera pose (RGB and RGB-D) shown in dataloader.py. And I found that the RGB-D mode needs the pre-computed camera coordinate files (/eye/) which is not provided in datasets. I also read the codes of DSAC* and found it offers an implement to get the pre-computed camera coordinate files from depth maps and RGB images. However, it seems that it can't be directly apply to your dataset. Do you have any idea to generate the pre-computed camera coordinate files? 
  Besides, do you use wechat?  If possible, I would like to add a wechat friend with you to facilitate subsequent communication.  Thanks a lot!

Best wishes,
Tu

**Comment by qiyan98** [comment]
Hi Tu,

No worries. Indeed, we didn't use the `RGB-D` setup in our dataloader because we could obtain high-quality scene coordinates (i.e., 3D coordinates per pixel in the world coordinate system) through ray-tracing in Cesium.

If I remember correctly, the `RGB-D` data loading aims to approximately reconstruct the scene coordinates using a depth map and camera intrinsic parameters. The DSAC* paper did this because some benchmark datasets (e.g., 7Scenes) only have depth maps and not accurate scene coordinates.

I'm happy to collaborate with you further on this topic. You can send me an email at qi.yan@ece.ubc.ca to discuss further (exchange wechat, etc.).

Best,
Qi
